# Generated by Django 4.0.6 on 2022-08-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Rid', models.AutoField(primary_key=True, serialize=False)),
                ('Rnombre', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'usuarios_rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('Unombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('documento', models.IntegerField(verbose_name='documento')),
                ('celular', models.CharField(max_length=13, unique=True)),
                ('tipo_documento', models.CharField(choices=[('C.C', 'C.C'), ('T.I', 'T.I'), ('C.E', 'C.E')], max_length=3, verbose_name='Tipo documento')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulado', 'Anulado')], default='Activo', max_length=10, verbose_name='Estado')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol', verbose_name='Rol')),
            ],
            options={
                'db_table': 'usuarios_usuario',
            },
        ),
    ]
