# Generated by Django 4.1.1 on 2022-09-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.IntegerField(verbose_name='Documento'),
        ),
    ]
