# Generated by Django 4.1.1 on 2022-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.IntegerField(unique=True, verbose_name='Documento'),
        ),
    ]
