# Generated by Django 4.0.6 on 2022-09-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rol_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='estado',
        ),
    ]
