# Generated by Django 4.0.6 on 2022-08-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(default=0, verbose_name='Precio venta'),
        ),
    ]
