# Generated by Django 4.1.1 on 2022-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje',
            field=models.IntegerField(max_length=10, verbose_name='Porcentaje'),
        ),
    ]
