# Generated by Django 4.1.1 on 2022-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talla',
            name='tipo_talla',
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='talla',
            name='nombre',
            field=models.CharField(max_length=10, unique=True, verbose_name='nombre'),
        ),
    ]
