# Generated by Django 4.1.1 on 2022-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_talla_tipo_talla_alter_color_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje',
            field=models.IntegerField(verbose_name='Porcentaje'),
        ),
    ]
