# Generated by Django 4.0.6 on 2022-08-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pago',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_pago',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
